using Factory.Infrastructure;
using Factory.Orchestrator;
using Serilog;

var builder = Host.CreateApplicationBuilder(args);
builder.Services.AddSerilog(configuration => configuration.WriteTo.Console().WriteTo.File("logs/orchestrator-.log", rollingInterval: RollingInterval.Day));
builder.Services.AddFactoryTelemetry(builder.Configuration, "Factory.Orchestrator");
builder.Services.AddFactoryInfrastructure(builder.Configuration);
builder.Services.AddHttpClient();
builder.Services.AddSingleton<PrepareRepositoryStep>();
builder.Services.AddSingleton<CreateWorktreeStep>();
builder.Services.AddSingleton<WriteContextStep>();
builder.Services.AddSingleton<AgentSelector>();
builder.Services.AddSingleton<RunAgentStep>();
builder.Services.AddSingleton<CollectDiffStep>();
builder.Services.AddSingleton<ValidateStep>();
builder.Services.AddSingleton<SmokeTestStep>();
builder.Services.AddSingleton<SyncBaseBranchStep>();
builder.Services.AddSingleton<PreparePublicationStep>();
builder.Services.AddSingleton<ReviewStep>();
builder.Services.AddSingleton<TaskGitHubNotifier>();
builder.Services.AddSingleton<TaskExecutor>();
builder.Services.AddSingleton<LeaseMonitor>();
builder.Services.AddSingleton<PublicationExecutor>();
builder.Services.AddSingleton<WorktreeCleanupExecutor>();
builder.Services.AddHostedService<Worker>();
builder.Services.AddHostedService<PublicationWorker>();
builder.Services.AddHostedService<WorktreeCleanupWorker>();
await builder.Build().RunAsync();
