"use client";
import { use } from "react";
import { useQuery } from "@tanstack/react-query";
import { CheckCircle2, Circle, XCircle } from "lucide-react";
import { z } from "zod";
import { Badge, Duration, Empty } from "@/components/ui";
import { getJson, taskSchema } from "@/lib/api";

const step=z.object({id:z.string(),runId:z.string(),stepType:z.string(),status:z.string(),startedAt:z.string(),completedAt:z.string().nullable(),durationMs:z.number().nullable(),attempt:z.number(),error:z.string().nullable(),output:z.string().nullable()});
const details=z.object({task:taskSchema,issue:z.object({issueNumber:z.number(),title:z.string(),body:z.string(),state:z.string(),author:z.string(),labels:z.array(z.string()).nullable()}).nullable(),runs:z.array(z.record(z.string(),z.unknown())),steps:z.array(step),agentRuns:z.array(z.object({id:z.string(),agent:z.string(),status:z.string(),exitCode:z.number().nullable(),stdout:z.string().nullable(),stderr:z.string().nullable(),quotaDetected:z.boolean(),attemptNumber:z.number()}))});

export default function TaskDetails({params}:{params:Promise<{id:string}>}) { const {id}=use(params); const {data,error}=useQuery({queryKey:["task",id],queryFn:()=>getJson(`/api/tasks/${id}`,details)});
  if(error)return <Empty>Unable to load this task</Empty>; if(!data)return <Empty>Loading task…</Empty>; const {task,issue}=data;
  return <div className="space-y-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="eyebrow">Task · {task.repository} {task.issueNumber&&`#${task.issueNumber}`}</p><h1 className="mt-1 text-2xl font-semibold">{task.title}</h1><p className="mt-1 text-sm text-slate-500">Created {new Date(task.createdAt).toLocaleString()}</p></div><Badge value={task.status}/></div>
    <div className="grid gap-5 xl:grid-cols-[1fr_2fr]"><div className="space-y-5"><section className="panel p-4"><p className="eyebrow">Execution metadata</p><dl className="mt-4 grid grid-cols-[7rem_1fr] gap-y-3 text-xs"><dt className="text-slate-500">Agent</dt><dd>{task.agent}</dd><dt className="text-slate-500">Duration</dt><dd><Duration seconds={task.durationSeconds}/></dd><dt className="text-slate-500">Branch</dt><dd className="truncate font-mono">{task.branchName??"Not assigned"}</dd><dt className="text-slate-500">Worktree</dt><dd className="break-all font-mono text-[11px]">{task.worktreePath??"Not created"}</dd></dl></section><section className="panel p-4"><p className="eyebrow">GitHub issue</p>{issue?<div className="mt-3"><div className="flex gap-2">{issue.labels?.map(l=><span className="badge blue" key={l}>{l}</span>)}</div><p className="mt-3 whitespace-pre-wrap text-xs leading-5 text-slate-400">{issue.body||"No description."}</p></div>:<p className="mt-3 text-xs text-slate-500">No linked issue</p>}</section></div>
      <section className="panel overflow-hidden"><div className="border-b border-[var(--border)] px-4 py-3"><p className="text-sm font-semibold">Execution timeline</p><p className="text-xs text-slate-500">Orchestrator-owned steps and validation</p></div><div className="p-4">{data.steps.length?data.steps.map((s,i)=>{const Icon=s.status==="Succeeded"?CheckCircle2:s.status==="Failed"?XCircle:Circle;return <div className="relative flex gap-4 pb-6 last:pb-0" key={s.id}>{i<data.steps.length-1&&<div className="absolute left-[9px] top-5 h-full w-px bg-[var(--border)]"/>}<Icon className={`relative z-10 size-5 bg-[var(--panel)] ${s.status==="Succeeded"?"text-emerald-400":s.status==="Failed"?"text-red-400":"text-slate-600"}`}/><div className="min-w-0 flex-1"><div className="flex justify-between gap-3"><p className="text-sm font-medium">{s.stepType.replace(/([a-z])([A-Z])/g,"$1 $2")}</p><span className="text-xs text-slate-500"><Duration seconds={s.durationMs? s.durationMs/1000:null}/></span></div><p className="mt-1 text-xs text-slate-500">Attempt {s.attempt} · {s.status}</p>{s.error&&<pre className="mt-3 max-h-36 overflow-auto rounded bg-black/30 p-3 text-[11px] text-red-300">{s.error}</pre>}{s.output&&<details className="mt-2"><summary className="cursor-pointer text-xs text-slate-500">Output</summary><pre className="mt-2 max-h-64 overflow-auto rounded bg-black/30 p-3 text-[11px] text-slate-400">{s.output}</pre></details>}</div></div>}):<Empty>No execution steps yet</Empty>}</div></section></div>
    {data.agentRuns.map(r=><section className="panel overflow-hidden" key={r.id}><div className="flex items-center justify-between border-b border-[var(--border)] px-4 py-3"><div><p className="text-sm font-semibold">{r.agent} · attempt {r.attemptNumber}</p><p className="text-xs text-slate-500">Exit code {r.exitCode??"—"}{r.quotaDetected?" · quota detected":""}</p></div><Badge value={r.status}/></div><div className="grid md:grid-cols-2"><Log title="stdout" value={r.stdout}/><Log title="stderr" value={r.stderr}/></div></section>)}
  </div>;
}
function Log({title,value}:{title:string;value:string|null}){return <div className="min-w-0 border-r border-[var(--border)] p-4 last:border-0"><p className="eyebrow">{title}</p><pre className="mt-3 max-h-72 overflow-auto whitespace-pre-wrap text-[11px] leading-5 text-slate-400">{value||"No output"}</pre></div>}
